[2024-10-08T14:30:51.495+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T14:30:51.510+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_dag.analyze_data manual__2024-10-08T14:30:01.235157+00:00 [queued]>
[2024-10-08T14:30:51.516+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_dag.analyze_data manual__2024-10-08T14:30:01.235157+00:00 [queued]>
[2024-10-08T14:30:51.516+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-08T14:30:51.524+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): analyze_data> on 2024-10-08 14:30:01.235157+00:00
[2024-10-08T14:30:51.530+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T14:30:51.532+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2024-10-08T14:30:51.533+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_dag', 'analyze_data', 'manual__2024-10-08T14:30:01.235157+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpj47aalz1']
[2024-10-08T14:30:51.534+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask analyze_data
[2024-10-08T14:30:51.579+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_dag.analyze_data manual__2024-10-08T14:30:01.235157+00:00 [running]> on host d2aa38be11ee
[2024-10-08T14:30:51.630+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_dag' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T14:30:01.235157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T14:30:01.235157+00:00'
[2024-10-08T14:30:51.631+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T14:30:51.643+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-08T14:30:51.643+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/runtime.py /opt/***/scripts/analyze.py']
[2024-10-08T14:30:51.650+0000] {subprocess.py:86} INFO - Output:
[2024-10-08T14:30:51.919+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-08T14:30:51.929+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/analyze.py", line 2, in <module>
[2024-10-08T14:30:51.930+0000] {subprocess.py:93} INFO -     import dask.dataframe as dd
[2024-10-08T14:30:51.930+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'dask'
[2024-10-08T14:30:52.870+0000] {subprocess.py:93} INFO - 
[2024-10-08T14:30:52.874+0000] {subprocess.py:93} INFO - Starting script: /opt/***/scripts/analyze.py
[2024-10-08T14:30:52.875+0000] {subprocess.py:93} INFO - Finished script: /opt/***/scripts/analyze.py
[2024-10-08T14:30:52.876+0000] {subprocess.py:93} INFO - Execution time: 1.01 seconds
[2024-10-08T14:30:52.876+0000] {subprocess.py:93} INFO - Average CPU usage: 0.00%
[2024-10-08T14:30:52.877+0000] {subprocess.py:93} INFO - Maximum RAM usage: 0.00 MB
[2024-10-08T14:30:52.877+0000] {subprocess.py:93} INFO - 
[2024-10-08T14:30:52.878+0000] {subprocess.py:93} INFO - ===== Summary =====
[2024-10-08T14:30:52.878+0000] {subprocess.py:93} INFO - Script: /opt/***/scripts/analyze.py
[2024-10-08T14:30:52.879+0000] {subprocess.py:93} INFO -   Execution time: 1.01 seconds
[2024-10-08T14:30:52.879+0000] {subprocess.py:93} INFO -   Average CPU usage: 0.00%
[2024-10-08T14:30:52.880+0000] {subprocess.py:93} INFO -   Maximum RAM usage: 0.00 MB
[2024-10-08T14:30:52.881+0000] {subprocess.py:93} INFO - 
[2024-10-08T14:30:52.882+0000] {subprocess.py:93} INFO - Total execution time for all scripts: 1.01 seconds
[2024-10-08T14:30:52.896+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-08T14:30:52.942+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T14:30:52.943+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline_dag, task_id=analyze_data, run_id=manual__2024-10-08T14:30:01.235157+00:00, execution_date=20241008T143001, start_date=20241008T143051, end_date=20241008T143052
[2024-10-08T14:30:53.036+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-08T14:30:53.072+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T14:30:53.074+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
